spring:
  application:
    name: authservice
  datasource:
    url: jdbc:mysql://mysql:3306/money_tracker
    username: root
    password: secret_pw
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
  config:
    import: optional:file:authservice-dev.env[.properties]
  kafka:
    bootstrap-servers: kafka:29092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
    topic:
      name: auth_users


server:
  port: 9898

